# Generated by Django 6.1 on 2026-08-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(default='N/A', max_length=100)),
                ('raza', models.CharField(max_length=100, null=True)),
                ('edad', models.IntegerField(null=True)),
            ],
        ),
    ]
