# Generated by Django 6.1 on 2026-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='nombre',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='raza',
            field=models.CharField(max_length=100),
        ),
    ]
